import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;

export const dynamic = 'force-dynamic';

// 349 Halo sets scraped from wiki.halo.fr/Mega_Construx
// Covers 2009–2023, both Mega Bloks (pre-2015) and Mega Construx (2015+)
const HALO_SETS = [
  { name: 'UNSC Warthog', set_number: '96805', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 173, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Turret', set_number: '96801', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 54, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Scorpion', set_number: '96807', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 278, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Hornet', set_number: '96806', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 159, retail_price: 19.99, is_retired: true },
  { name: 'Covenant Ghost', set_number: '96802', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 72, retail_price: 9.99, is_retired: true },
  { name: 'Battle Unit', set_number: '96814', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 20, retail_price: 14.99, is_retired: true },
  { name: 'Aerial Ambush', set_number: '96810', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2009, piece_count: 376, retail_price: 39.99, is_retired: true },
  { name: 'UNSC Troop Transport', set_number: '96866', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 165, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Shortsword', set_number: '96835', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 471, retail_price: 39.99, is_retired: true },
  { name: 'UNSC Red Weapons Pack', set_number: '96838', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 24, retail_price: 4.99, is_retired: true },
  { name: 'UNSC Mongoose', set_number: '96849', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 76, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Hornet Attack', set_number: '96867', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 256, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Gremlin', set_number: '96818', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 226, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Gausshog vs Covenant Locust', set_number: '96823', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 385, retail_price: 39.99, is_retired: true },
  { name: 'UNSC Flame Marine', set_number: '29678', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 27, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Flame Marine', set_number: '29679', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 27, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Arctic Wolverine', set_number: '96852', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 298, retail_price: 29.99, is_retired: true },
  { name: 'ODST Sniper', set_number: '96861', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 26, retail_price: 11.99, is_retired: true },
  { name: 'ODST Heavy Weapons Specialist', set_number: '96863', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 27, retail_price: 11.99, is_retired: true },
  { name: 'ODST Hawk', set_number: '96850', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 328, retail_price: 29.99, is_retired: true },
  { name: 'Combat Unit III', set_number: '96822', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 13, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Pelican Dropship', set_number: '96824', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 944, retail_price: 59.99, is_retired: true },
  { name: 'Covenant Wraith', set_number: '96832', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 459, retail_price: 29.99, is_retired: true },
  { name: 'Covenant Weapons Pack', set_number: '96839', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 22, retail_price: 4.99, is_retired: true },
  { name: 'Covenant Combat Unit', set_number: '96828', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 19, retail_price: 9.99, is_retired: true },
  { name: 'Covenant Brute Chopper', set_number: '96845', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 74, retail_price: 9.99, is_retired: true },
  { name: 'Combat Unit II', set_number: '96821', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2010, piece_count: 15, retail_price: 9.99, is_retired: true },
  { name: 'Versus: Covenant Locust Attack', set_number: '96965', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 284, retail_price: 29.99, is_retired: true },
  { name: 'Versus: Assault on High Ground', set_number: '96967', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 542, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Weapons Pack II', set_number: '96920', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 29, retail_price: 4.99, is_retired: true },
  { name: 'UNSC Red Combat Unit', set_number: '96865', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 24, retail_price: 9.99, is_retired: true },
  { name: 'Red Team Weapons Pack', set_number: '96956', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 21, retail_price: 4.99, is_retired: true },
  { name: 'Red Covenant Combat Unit', set_number: '96919', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 34, retail_price: 9.99, is_retired: true },
  { name: 'Red Combat Unit', set_number: '96961', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 41, retail_price: 9.99, is_retired: true },
  { name: 'ODST Covert Ops Specialist', set_number: '96926', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 27, retail_price: 11.99, is_retired: true },
  { name: 'ODST Covenant Invasion', set_number: '96853', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 669, retail_price: 49.99, is_retired: true },
  { name: 'Halo Battlescape', set_number: '96837', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 80, retail_price: 39.99, is_retired: true },
  { name: 'Anniversary Edition: UNSC Warthog', set_number: '96973', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 734, retail_price: 49.99, is_retired: true },
  { name: 'Anniversary Edition: Floodgate', set_number: '96971', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 273, retail_price: 29.99, is_retired: true },
  { name: 'Covenant Weapons Pack II', set_number: '96921', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 28, retail_price: 4.99, is_retired: true },
  { name: 'Covenant Brute Prowler', set_number: '96869', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 173, retail_price: 19.99, is_retired: true },
  { name: 'Covenant Banshee', set_number: '96859', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 97, retail_price: 9.99, is_retired: true },
  { name: 'Blue Team Weapons Pack', set_number: '96957', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 22, retail_price: 4.99, is_retired: true },
  { name: 'Blue Team Combat Unit', set_number: '96962', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 42, retail_price: 9.99, is_retired: true },
  { name: 'Battle Unit II', set_number: '96915', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 20, retail_price: 14.99, is_retired: true },
  { name: 'Arctic Combat Unit', set_number: '96858', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 25, retail_price: 9.99, is_retired: true },
  { name: 'Anniversary Edition: UNSC Troop Pack', set_number: '96970', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 120, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Weapons Pack', set_number: '96946', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 29, retail_price: 5.99, is_retired: true },
  { name: 'UNSC Silver Combat Unit', set_number: '96911', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 42, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Rockethog vs Anti Aircraft Gun', set_number: '96923', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 537, retail_price: 59.99, is_retired: true },
  { name: 'UNSC Falcon', set_number: '96940', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 503, retail_price: 39.99, is_retired: true },
  { name: 'UNSC Elephant', set_number: '96942', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 1273, retail_price: 99.99, is_retired: true },
  { name: 'ODST Ambush', set_number: '96931', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 69, retail_price: 11.99, is_retired: true },
  { name: 'EVA\'s Last Stand', set_number: '96937', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 169, retail_price: 21.99, is_retired: true },
  { name: 'Covenant Weapon Pack', set_number: '96947', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 24, retail_price: 5.99, is_retired: true },
  { name: 'Covenant Phantom', set_number: '96941', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 906, retail_price: 79.99, is_retired: true },
  { name: 'Covenant Drop Pod: Zealot Elite', set_number: '96933', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 23, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Drop Pod: Combat Elite', set_number: '96932', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 22, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Assault Unit', set_number: '96912', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2011, piece_count: 29, retail_price: 11.99, is_retired: true },
  { name: 'Halo Series 3', set_number: '96954', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 3, retail_price: 2.99, is_retired: true },
  { name: 'Halo Series 5', set_number: '96978', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 3, retail_price: 2.99, is_retired: true },
  { name: 'Halo Series 5.5', set_number: '97013', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 3, retail_price: 2.99, is_retired: true },
  { name: 'UNSC Spade vs. Skirmisher', set_number: '96981', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 204, retail_price: 21.99, is_retired: true },
  { name: 'UNSC Desert Combat Unit', set_number: '96958', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 53, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Armory Pack', set_number: '96951', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 28, retail_price: 5.99, is_retired: true },
  { name: 'Halo Battlescape II', set_number: '96983', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 98, retail_price: 44.99, is_retired: true },
  { name: 'Flood Pod: Elite Combat Form', set_number: '96929', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 28, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Crimson Combat Unit', set_number: '96959', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 47, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Shade Turret', set_number: '96949', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 68, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Revenant Attack', set_number: '96982', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 281, retail_price: 32.99, is_retired: true },
  { name: 'Covenant Drop Pod: Elite Ultra', set_number: '96928', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 24, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Armory Pack', set_number: '96952', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 29, retail_price: 5.99, is_retired: true },
  { name: 'Orbital Banshee Blitz', set_number: '97010', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 204, retail_price: 21.99, is_retired: true },
  { name: 'Covenant Silver Combat Unit', set_number: '97002', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 42, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Cobalt Combat Unit', set_number: '97001', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 48, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Crimson Combat Unit', set_number: '97028', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 47, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Desert Combat Unit', set_number: '97027', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 53, retail_price: 11.99, is_retired: true },
  { name: 'Brute Chieftain Charge', set_number: '96993', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 72, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Armory Pack II', set_number: '96997', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 22, retail_price: 5.99, is_retired: true },
  { name: 'UNSC Armory Pack II', set_number: '96996', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 22, retail_price: 5.99, is_retired: true },
  { name: 'Covenant Armory Pack', set_number: '97024', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 29, retail_price: 5.99, is_retired: true },
  { name: 'UNSC Armory Pack', set_number: '97023', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 28, retail_price: 5.99, is_retired: true },
  { name: 'Countdown', set_number: '97017', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 1241, retail_price: 99.99, is_retired: true },
  { name: 'UNSC Rhino', set_number: '97016', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 822, retail_price: 84.99, is_retired: true },
  { name: 'Covenant Seraph', set_number: '97015', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 566, retail_price: 64.99, is_retired: true },
  { name: 'Covenant Wraith', set_number: '97014', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 637, retail_price: 44.99, is_retired: true },
  { name: 'Battlescape III', set_number: '97029', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 100, retail_price: 44.99, is_retired: true },
  { name: 'Warthog Resistance', set_number: '97011', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 285, retail_price: 32.99, is_retired: true },
  { name: 'Versus: Snowbound Combat Unit', set_number: '97065', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 36, retail_price: 11.99, is_retired: true },
  { name: 'Versus: Snowbound Weapons Pack I', set_number: '97041', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 21, retail_price: 5.99, is_retired: true },
  { name: 'Versus: Snowbound Weapons Pack II', set_number: '97043', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 29, retail_price: 5.99, is_retired: true },
  { name: 'Brute Prowler Attack', set_number: '97004', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 205, retail_price: 32.99, is_retired: true },
  { name: 'Forward Unto Dawn', set_number: '97117', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 2877, retail_price: 249.99, is_retired: true },
  { name: 'Flood Siege', set_number: '97071', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 426, retail_price: 54.99, is_retired: true },
  { name: 'Covert Ops: UNSC Wolverine', set_number: '97072', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 330, retail_price: 32.99, is_retired: true },
  { name: 'Covert Ops: Battle Unit', set_number: '97070', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 47, retail_price: 14.99, is_retired: true },
  { name: 'Versus: Snowbound Battlescape', set_number: '97068', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 100, retail_price: 44.99, is_retired: true },
  { name: 'Versus: Snowbound Highbase', set_number: '97069', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 438, retail_price: 34.99, is_retired: true },
  { name: 'Snowbound: UNSC Rockethog', set_number: '97003', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 222, retail_price: 49.99, is_retired: true },
  { name: 'Covenant Drop Pod: Elite General', set_number: '97106', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 20, retail_price: 11.99, is_retired: true },
  { name: 'ODST Recon Specialist', set_number: '97105', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2012, piece_count: 31, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Pelican Gunship', set_number: '97129', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 1161, retail_price: 99.99, is_retired: true },
  { name: 'Cauldron Clash', set_number: '97118', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 518, retail_price: 44.99, is_retired: true },
  { name: 'UNSC Mantis', set_number: '97115', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 443, retail_price: 32.99, is_retired: true },
  { name: 'Covenant Spectre Ambush', set_number: '97110', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 183, retail_price: 21.99, is_retired: true },
  { name: 'Flood Pod: Elite Combat Form', set_number: '97075', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 28, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Drop Pod: Elite Ultra', set_number: '97074', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 24, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Cryo Bay', set_number: '97088', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 72, retail_price: 11.99, is_retired: true },
  { name: 'Covenant Combat Cobalt Unit', set_number: '97084', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 38, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Combat Orange Unit', set_number: '97083', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 37, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Ammo Pack I', set_number: '97037', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 23, retail_price: 5.99, is_retired: true },
  { name: 'Last Man Standing Zombie Pack', set_number: '97199', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 72, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Cyclops Desert Strike', set_number: '97007', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 47, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Cyclops Jungle Strike', set_number: '97006', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 47, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Hornet vs. Covenant Vampire', set_number: '97123', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 684, retail_price: 69.99, is_retired: true },
  { name: 'UNSC Anti-Armor Cobra', set_number: '97139', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 460, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Night Ops Gausshog', set_number: '97134', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 239, retail_price: 32.99, is_retired: true },
  { name: 'UNSC Light Assault VTOL', set_number: '97102', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 169, retail_price: 21.99, is_retired: true },
  { name: 'UNSC Attack Cyclops', set_number: '97108', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 54, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Arctic Cyclops', set_number: '97107', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 63, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Siege Bike', set_number: '97116', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 72, retail_price: 11.99, is_retired: true },
  { name: 'Brute Battle Unit', set_number: '97085', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 37, retail_price: 11.99, is_retired: true },
  { name: 'ODST Battle Unit', set_number: '97082', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 42, retail_price: 11.99, is_retired: true },
  { name: 'UNSC C&C Console', set_number: '97131', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 60, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Hangar Deck', set_number: '97133', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 53, retail_price: 9.99, is_retired: true },
  { name: 'Forerunner Terminal', set_number: '97170', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 69, retail_price: 9.99, is_retired: true },
  { name: 'Collector\'s Edition Pack', set_number: '97205', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 59, retail_price: 19.99, is_retired: true },
  { name: 'Blue Series Falcon', set_number: '97204', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 450, retail_price: 39.99, is_retired: true },
  { name: 'Blue Series Rockethog', set_number: '97159', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 285, retail_price: 24.99, is_retired: true },
  { name: 'Blue Series Banshee', set_number: '97202', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 109, retail_price: 19.99, is_retired: true },
  { name: 'Flood Hunter\'s UNSC Falcon', set_number: '97173', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 460, retail_price: 54.99, is_retired: true },
  { name: 'Flood Hunters Battle Unit', set_number: '97160', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 72, retail_price: 14.99, is_retired: true },
  { name: 'Red UNSC Spade', set_number: '97158', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 212, retail_price: 32.99, is_retired: true },
  { name: 'Covenant Weapons Pack', set_number: '97076', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 26, retail_price: 5.99, is_retired: true },
  { name: 'UNSC Weapons Pack', set_number: '97165', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 24, retail_price: 5.99, is_retired: true },
  { name: 'Forerunner Weapons Pack', set_number: '97166', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 20, retail_price: 5.99, is_retired: true },
  { name: 'UNSC Mammoth', set_number: '97174', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 2030, retail_price: 179.99, is_retired: true },
  { name: 'Blue Series Elite Pack', set_number: '97285', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 29, retail_price: 5.99, is_retired: true },
  { name: 'Blue Series ODST Pack', set_number: '97284', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2013, piece_count: 25, retail_price: 5.99, is_retired: true },
  { name: 'Spartan IV Battle Pack', set_number: '97208', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 33, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Weapons Pack II', set_number: '97207', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 28, retail_price: 5.99, is_retired: true },
  { name: 'Metallic Series ODST Drop Pods', set_number: '97417', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 11, retail_price: 3.99, is_retired: true },
  { name: 'Metallic Series ODST Drop Pods', set_number: '97418', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 11, retail_price: 3.99, is_retired: true },
  { name: 'Metallic Series ODST Drop Pods', set_number: '97419', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 11, retail_price: 3.99, is_retired: true },
  { name: 'Metallic Series ODST Drop Pods', set_number: '97420', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 11, retail_price: 3.99, is_retired: true },
  { name: 'UNSC Infinity Armor Bay', set_number: '97262', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 189, retail_price: 21.99, is_retired: true },
  { name: 'Micro-Fleet Mantis Invasion', set_number: '97270', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 80, retail_price: 14.99, is_retired: true },
  { name: 'Micro-Fleet Warthog Attack', set_number: '97216', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 93, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Offworld Cyclops', set_number: '97214', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 51, retail_price: 14.99, is_retired: true },
  { name: 'Rapid Attack Covenant Ghost', set_number: '97213', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 104, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Quad Walker', set_number: '97263', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 342, retail_price: 32.99, is_retired: true },
  { name: 'Micro-Fleet Hornet Assault', set_number: '97224', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 79, retail_price: 14.99, is_retired: true },
  { name: 'Police Cruiser Standoff', set_number: '97452', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 224, retail_price: 19.99, is_retired: true },
  { name: 'Police Air Support Hornet', set_number: '97429', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 390, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Flame Warthog', set_number: '97449', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 207, retail_price: 24.99, is_retired: true },
  { name: 'Sector 12 Police Cyclops', set_number: '97326', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 58, retail_price: 14.99, is_retired: true },
  { name: 'Spartan Assault Battle Pack', set_number: '97336', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 57, retail_price: 11.99, is_retired: true },
  { name: 'UNSC Fireteam Crimson', set_number: '97349', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 132, retail_price: 14.99, is_retired: true },
  { name: 'Forerunner Weapons Pack II', set_number: '97360', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 34, retail_price: 5.99, is_retired: true },
  { name: 'Covenant Weapons Pack II', set_number: '97359', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 28, retail_price: 5.99, is_retired: true },
  { name: 'Drop Pod Metallic Purple Elite', set_number: '97356', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 10, retail_price: 3.99, is_retired: true },
  { name: 'Drop Pod Metallic Crimson Elite', set_number: '97355', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 10, retail_price: 3.99, is_retired: true },
  { name: 'Drop Pod Metallic Cobalt ODST', set_number: '97354', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 19, retail_price: 3.99, is_retired: true },
  { name: 'Drop Pod Metallic Copper ODST', set_number: '97353', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 19, retail_price: 3.99, is_retired: true },
  { name: 'UNSC Elephant Troop Carrier', set_number: '97381', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 1311, retail_price: 99.99, is_retired: true },
  { name: 'UNSC Fireteam Venom', set_number: '97350', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 128, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Wombat Recon Drone', set_number: '97451', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 89, retail_price: 9.99, is_retired: true },
  { name: 'UNSC All-Terrain Mongoose', set_number: '97339', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 82, retail_price: 9.99, is_retired: true },
  { name: 'Micro-Fleet Falcon', set_number: '97341', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 70, retail_price: 14.99, is_retired: true },
  { name: 'Last Man Standing Zombie Pack II', set_number: '97514', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 85, retail_price: 14.99, is_retired: true },
  { name: 'Containment Armory', set_number: '97516', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 53, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Broadsword Midnight Strike', set_number: '97380', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 716, retail_price: 59.99, is_retired: true },
  { name: 'Revenant Raid', set_number: '97517', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 275, retail_price: 32.99, is_retired: true },
  { name: 'Wireless Attack Mantis', set_number: '97450', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 120, retail_price: 59.99, is_retired: true },
  { name: 'Flood Invasion', set_number: '97430', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 265, retail_price: 39.99, is_retired: true },
  { name: 'Anniversary Collection: Hierarch\'s Shadow Convoy', set_number: '97521', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 485, retail_price: 54.99, is_retired: true },
  { name: 'Containment Outpost Patrol', set_number: '97515', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 236, retail_price: 29.99, is_retired: true },
  { name: 'Anniversary Collection: Battleground', set_number: '97519', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 61, retail_price: 14.99, is_retired: true },
  { name: 'Covenant Scarab', set_number: '97694', category: 'Mega', theme: 'Mega Bloks · Halo', year_released: 2014, piece_count: 3340, retail_price: 249.99, is_retired: true },
  { name: 'UNSC Sierra Squad', set_number: 'CND01', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 155, retail_price: 14.99, is_retired: true },
  { name: 'Covenant Drone Outbreak', set_number: 'CND03', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 378, retail_price: 29.99, is_retired: true },
  { name: 'Booster Frame', set_number: 'CND02', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 277, retail_price: 19.99, is_retired: true },
  { name: 'Heavy Assault Cyclops', set_number: 'CNC98', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 76, retail_price: 14.99, is_retired: true },
  { name: 'NMPD Customizer Pack', set_number: 'CNC96', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 55, retail_price: 7.99, is_retired: true },
  { name: 'Spartan Customizer Pack', set_number: 'CNC95', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 66, retail_price: 7.99, is_retired: true },
  { name: 'UNSC Fireteam Eagle', set_number: 'CND00', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 140, retail_price: 14.99, is_retired: true },
  { name: 'Covenant Commander', set_number: 'CNH23', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 97, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Victor Squad', set_number: 'CNK26', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 129, retail_price: 15.99, is_retired: true },
  { name: 'UNSC Fireteam Rhino', set_number: 'CNK25', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 117, retail_price: 15.99, is_retired: true },
  { name: 'Flood Infected Cyclops', set_number: 'CNH25', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 46, retail_price: 14.99, is_retired: true },
  { name: 'Damage Control Cyclops', set_number: 'CNG61', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 70, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Fireteam Taurus', set_number: 'CNG63', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 152, retail_price: 15.99, is_retired: true },
  { name: 'Covenant Armor Customizer Pack', set_number: 'CNH21', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 75, retail_price: 8.99, is_retired: true },
  { name: 'Covenant Weapons Customizer Pack', set_number: 'CNH22', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 52, retail_price: 8.99, is_retired: true },
  { name: 'Drop Pod Metallic Blue Elite', set_number: 'CNJ46', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 26, retail_price: 4.99, is_retired: true },
  { name: 'Drop Pod Metallic Stealth ODST', set_number: 'CNJ43', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 22, retail_price: 4.99, is_retired: true },
  { name: 'Drop Pod Metallic Jungle ODST', set_number: 'CNJ44', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 22, retail_price: 4.99, is_retired: true },
  { name: 'Drop Pod Metallic Arctic ODST', set_number: 'CNJ45', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 22, retail_price: 4.99, is_retired: true },
  { name: 'Promethean Warriors', set_number: 'CNG64', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 94, retail_price: 15.99, is_retired: true },
  { name: 'Scorpion\'s Sting', set_number: 'CNG68', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 616, retail_price: 54.99, is_retired: true },
  { name: 'Phaeton Gunship', set_number: 'CNG67', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 455, retail_price: 44.99, is_retired: true },
  { name: 'Banshee Strike', set_number: 'CNG65', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 173, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Vulture Gunship', set_number: 'CNG71', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 1031, retail_price: 89.99, is_retired: true },
  { name: 'UNSC Firebase', set_number: 'CNG69', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 637, retail_price: 64.99, is_retired: true },
  { name: 'UNSC Attack Gausshog', set_number: 'CNG66', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 229, retail_price: 24.99, is_retired: true },
  { name: 'UNSC Gungoose', set_number: 'CNH24', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 97, retail_price: 9.99, is_retired: true },
  { name: 'Outlands Skirmish', set_number: 'CNH01', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 236, retail_price: 24.99, is_retired: true },
  { name: 'Smuggler Intercept', set_number: 'CNH00', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 590, retail_price: 54.99, is_retired: true },
  { name: 'ODST Troop Pack', set_number: 'CNG99', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 102, retail_price: 15.99, is_retired: true },
  { name: 'Versus Troop Pack', set_number: 'CNH04', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 115, retail_price: 15.99, is_retired: true },
  { name: 'NMPD Warthog', set_number: 'CNH06', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 213, retail_price: 32.99, is_retired: true },
  { name: 'NMPD Pelican Air Base', set_number: 'CPF71', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2015, piece_count: 1792, retail_price: 179.99, is_retired: true },
  { name: 'Spartan Armor Customizer Pack', set_number: 'DLB92', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 66, retail_price: 8.99, is_retired: true },
  { name: 'Promethean Armor Customizer Pack', set_number: 'DLB93', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 44, retail_price: 8.99, is_retired: true },
  { name: 'UNSC Fireteam Stingray', set_number: 'DLB95', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 150, retail_price: 8.99, is_retired: true },
  { name: 'Covenant Storm Lance', set_number: 'DLB96', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 114, retail_price: 15.99, is_retired: true },
  { name: 'Covenant Watch Tower', set_number: 'DKT68', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 239, retail_price: 19.99, is_retired: true },
  { name: 'Spartan IV Battle Pack III', set_number: 'DPP70', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 59, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Yankee Squad', set_number: 'DPJ88', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 143, retail_price: 15.99, is_retired: true },
  { name: 'Covenant Brute Lance', set_number: 'DPJ89', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 130, retail_price: 15.99, is_retired: true },
  { name: 'UNSC Jackrabbit Blitz', set_number: 'DPJ90', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 81, retail_price: 9.99, is_retired: true },
  { name: 'Incinerator Cyclops', set_number: 'DPJ86', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 157, retail_price: 15.99, is_retired: true },
  { name: 'Strike Cyclops', set_number: 'DPJ87', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 157, retail_price: 15.99, is_retired: true },
  { name: 'ODST Armor Customizer Pack', set_number: 'DPJ83', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 62, retail_price: 8.99, is_retired: true },
  { name: 'Elite Weapons Customizer Pack', set_number: 'DPJ84', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 62, retail_price: 8.99, is_retired: true },
  { name: 'Brute Chopper Raid', set_number: 'DPJ91', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 221, retail_price: 19.99, is_retired: true },
  { name: 'Dual Mode UNSC Warthog', set_number: 'DPJ92', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 330, retail_price: 29.99, is_retired: true },
  { name: 'Covenant Wraith Ambush', set_number: 'DPJ93', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 640, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Kodiak Siege Cannon', set_number: 'DPJ94', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 868, retail_price: 69.99, is_retired: true },
  { name: 'UNSC Spade Rush', set_number: 'DPW93', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 215, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Kestrel Strike', set_number: 'DPW94', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 289, retail_price: 34.99, is_retired: true },
  { name: 'Arena Champions Battle Pack', set_number: 'DPW95', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 382, retail_price: 24.99, is_retired: true },
  { name: 'UNSC Cobra Clash', set_number: 'DPW96', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 648, retail_price: 59.99, is_retired: true },
  { name: 'Covenant Spirit Dropship', set_number: 'DPJ95', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2016, piece_count: 2281, retail_price: 199.99, is_retired: true },
  { name: 'Banished Ghost Rush', set_number: 'DXF01', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 90, retail_price: 9.99, is_retired: true },
  { name: 'Fireteam Osiris', set_number: 'DYH88', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 144, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Fireteam Shadow', set_number: 'DXF03', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 133, retail_price: 15.99, is_retired: true },
  { name: 'Swords of Sanghelios Combat Lance', set_number: 'DXF04', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 140, retail_price: 15.99, is_retired: true },
  { name: 'Blue Team', set_number: 'DYH87', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 146, retail_price: 19.99, is_retired: true },
  { name: 'Metallic Green Cryotube', set_number: 'DXF06', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 23, retail_price: 4.99, is_retired: true },
  { name: 'Metallic Copper Cryotube', set_number: 'DXF07', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 23, retail_price: 4.99, is_retired: true },
  { name: 'Metallic Silver Cryotube', set_number: 'DXF08', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 23, retail_price: 4.99, is_retired: true },
  { name: 'Metallic Blue Cryotube', set_number: 'DXF09', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 23, retail_price: 4.99, is_retired: true },
  { name: 'UNSC Brute Skirmish', set_number: 'DXF10', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 85, retail_price: 9.99, is_retired: true },
  { name: 'Desert Sniper Cyclops', set_number: 'DXF02', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 32, retail_price: 15.99, is_retired: true },
  { name: 'Spartan Armor Customizer Pack II', set_number: 'DXR56', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 67, retail_price: 8.99, is_retired: true },
  { name: 'Brute Weapons Customizer Pack', set_number: 'DXR57', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 57, retail_price: 8.99, is_retired: true },
  { name: 'OPERATION THRONE Drop Pod', set_number: 'FDY37', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 58, retail_price: 9.99, is_retired: true },
  { name: 'OPERATION STONEBREAK Drop Pod', set_number: 'FDY38', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 58, retail_price: 9.99, is_retired: true },
  { name: 'Corporate Security Cyclops', set_number: 'FDY48', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 154, retail_price: 15.99, is_retired: true },
  { name: 'Fireteam Dagger', set_number: 'FDY45', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 149, retail_price: 15.99, is_retired: true },
  { name: 'CTF Arctic Warthog', set_number: 'FDY52', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 311, retail_price: 29.99, is_retired: true },
  { name: 'Warzone Wasp Strike', set_number: 'FDY53', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 632, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Gungoose Rampage', set_number: 'FDY54', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 195, retail_price: 19.99, is_retired: true },
  { name: 'Arctic Jackrabbit Assault', set_number: 'FGR21', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 168, retail_price: 19.99, is_retired: true },
  { name: 'Faithful vs. Fallen Battle Pack', set_number: 'FRM20', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 434, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Builder\'s Forge', set_number: 'FDY56', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 383, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Wolverine Charge', set_number: 'FDY55', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 759, retail_price: 54.99, is_retired: true },
  { name: 'UNSC Marines Customizer Pack', set_number: 'FDY41', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2017, piece_count: 62, retail_price: 8.99, is_retired: true },
  { name: 'Speed Boost Power Pack', set_number: 'FMM82', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 31, retail_price: 6.99, is_retired: true },
  { name: 'Overshield Power Pack', set_number: 'FMM83', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 32, retail_price: 6.99, is_retired: true },
  { name: 'Operation Veritas Drop Pod', set_number: 'FMM84', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 56, retail_price: 9.99, is_retired: true },
  { name: 'Fireteam Castle', set_number: 'FMM86', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 125, retail_price: 14.99, is_retired: true },
  { name: 'ONI Strike Team', set_number: 'FMM87', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 106, retail_price: 14.99, is_retired: true },
  { name: 'Shields of Requiem Lance', set_number: 'FMM88', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 108, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Woodland Gungoose', set_number: 'FMM89', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 85, retail_price: 9.99, is_retired: true },
  { name: 'Banished Banshee Brawl', set_number: 'FMM90', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 219, retail_price: 19.99, is_retired: true },
  { name: 'Covenant Goblin Battlesuit', set_number: 'FMM91', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 218, retail_price: 19.99, is_retired: true },
  { name: 'Spartan CTF Base Crashers', set_number: 'FNR84', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 87, retail_price: 9.99, is_retired: true },
  { name: 'Damage Boost Power Pack', set_number: 'FPJ24', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 32, retail_price: 6.99, is_retired: true },
  { name: 'Active Camo Power Pack', set_number: 'FPJ25', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 31, retail_price: 6.99, is_retired: true },
  { name: 'Rocket Boost Power Pack', set_number: 'FVK10', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 32, retail_price: 6.99, is_retired: true },
  { name: 'Operation: Ocean Breaker Drop Pod', set_number: 'FVK11', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 58, retail_price: 9.99, is_retired: true },
  { name: 'Operation: Bronze Cobra Drop Pod', set_number: 'FVK12', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 57, retail_price: 9.99, is_retired: true },
  { name: 'Mission: Banished Turret Takedown', set_number: 'FVK29', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 123, retail_price: 14.99, is_retired: true },
  { name: 'Mission: Radar Wreckage', set_number: 'FVK30', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 130, retail_price: null, is_retired: true },
  { name: 'UNSC Blizzard Squad', set_number: 'FVK32', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 111, retail_price: null, is_retired: true },
  { name: 'Green Machine vs Marauder', set_number: 'FVK35', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 342, retail_price: 29.99, is_retired: true },
  { name: 'Forgehog vs Banished Goliath', set_number: 'FVK36', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 654, retail_price: 49.99, is_retired: true },
  { name: 'UNSC Infinity', set_number: 'FVK37', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 2456, retail_price: null, is_retired: true },
  { name: 'UNSC Frostraven vs. Decimus', set_number: 'FVK38', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2018, piece_count: 1489, retail_price: 119.99, is_retired: true },
  { name: 'Siege Armor Pack', set_number: 'GCM30', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 33, retail_price: 6.99, is_retired: true },
  { name: 'Covert Armor Pack', set_number: 'GCM31', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 33, retail_price: 6.99, is_retired: true },
  { name: 'Spartan-IV Team Battle', set_number: 'GCM37', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 107, retail_price: 14.99, is_retired: true },
  { name: 'Kinsano Cyclops Raid', set_number: 'GCM43', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 230, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Hornet Blitz', set_number: 'GCM44', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 207, retail_price: 19.99, is_retired: true },
  { name: 'ODST Squad Ambush', set_number: 'GCT34', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 99, retail_price: 14.99, is_retired: true },
  { name: 'Vector Tactical Power Pack', set_number: 'GFT47', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 31, retail_price: 6.99, is_retired: true },
  { name: 'Spartan Grenadier Armor Pack', set_number: 'GFT49', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 33, retail_price: 6.99, is_retired: true },
  { name: 'Warthog Run', set_number: 'GFT55', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 318, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Marine Defense', set_number: 'GFT67', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 94, retail_price: 14.99, is_retired: true },
  { name: 'Aerial Ambush', set_number: 'GGF43', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 541, retail_price: 49.99, is_retired: true },
  { name: 'Designer Series: UNSC Scorpion Tank', set_number: 'GGG61', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2019, piece_count: 1014, retail_price: 69.99, is_retired: true },
  { name: 'UNSC Mongoose', set_number: 'GCM45', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 89, retail_price: 9.99, is_retired: true },
  { name: 'Hermes Hammer Power Pack', set_number: 'GLB65', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 30, retail_price: 6.99, is_retired: true },
  { name: 'JFO Spartan Armor Pack', set_number: 'GLB66', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 33, retail_price: 6.99, is_retired: true },
  { name: 'Mark I Prototype Exosuit', set_number: 'GLB71', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 81, retail_price: 9.99, is_retired: true },
  { name: 'Breacher Exosuit', set_number: 'GLB72', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 89, retail_price: 9.99, is_retired: true },
  { name: 'Skyfire Exosuit', set_number: 'GLB73', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 81, retail_price: 9.99, is_retired: true },
  { name: 'Sword Base Invasion', set_number: 'GLB75', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 99, retail_price: 19.99, is_retired: true },
  { name: 'Skiff Intercept', set_number: 'GNB21', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 452, retail_price: 39.99, is_retired: true },
  { name: 'Banshee Breakout', set_number: 'GNB24', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 218, retail_price: 19.99, is_retired: true },
  { name: 'Warthog Rally', set_number: 'GNB25', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 314, retail_price: 39.99, is_retired: true },
  { name: 'Defense Point Showdown', set_number: 'GNB27', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 782, retail_price: 59.99, is_retired: true },
  { name: 'Pelican Inbound', set_number: 'GNB28', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 2024, retail_price: 149.99, is_retired: true },
  { name: 'Recon Getaway', set_number: 'GNB40', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 123, retail_price: 14.99, is_retired: true },
  { name: 'Master Chief vs Arbiter', set_number: 'GNN72', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 51, retail_price: null, is_retired: true },
  { name: 'Master Chief vs Brute Warrior', set_number: 'GNW38', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 52, retail_price: null, is_retired: true },
  { name: 'Energy Sword', set_number: 'GPB05', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 567, retail_price: 49.99, is_retired: true },
  { name: 'Building Box', set_number: 'GPT03', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 450, retail_price: 29.99, is_retired: true },
  { name: 'Turret Takedown', set_number: 'GRM99', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 98, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Combat Unit', set_number: 'GRN02', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 104, retail_price: 14.99, is_retired: true },
  { name: 'Mercenary Combat Unit', set_number: 'GRN03', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 101, retail_price: 14.99, is_retired: true },
  { name: 'Forerunner Ring Installation', set_number: 'GRN05', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 301, retail_price: 24.99, is_retired: true },
  { name: 'UNSC Spartan Armor Pack', set_number: 'GRN07', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 106, retail_price: 14.99, is_retired: true },
  { name: 'UNSC Marine Gear Pack', set_number: 'GRN08', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 111, retail_price: 14.99, is_retired: true },
  { name: 'Master Chief Helmet', set_number: 'GVN33', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 414, retail_price: 29.99, is_retired: true },
  { name: 'Hijacked Ghost', set_number: 'GVP42', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 128, retail_price: 14.99, is_retired: true },
  { name: 'Last Spartan Standing', set_number: 'GWY97', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 57, retail_price: 9.99, is_retired: true },
  { name: 'Capture the Flag', set_number: 'GWY98', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 59, retail_price: 9.99, is_retired: true },
  { name: 'Skull Control', set_number: 'GWY99', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 62, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Marine Platoon Pack', set_number: 'GXB00', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2020, piece_count: 138, retail_price: 19.99, is_retired: true },
  { name: 'Escape', set_number: 'GYG57', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2021, piece_count: 70, retail_price: 9.99, is_retired: true },
  { name: 'Chopper Takedown', set_number: 'GYG58', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2021, piece_count: 202, retail_price: 19.99, is_retired: true },
  { name: 'UNSC Razorback Blitz', set_number: 'GYG59', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2021, piece_count: 302, retail_price: 29.99, is_retired: true },
  { name: 'UNSC Wasp Onslaught', set_number: 'GYG60', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2021, piece_count: 409, retail_price: 39.99, is_retired: true },
  { name: 'Covenant Needler Collector Halo Infinite', set_number: 'HDC30', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 920, retail_price: 59.99, is_retired: true },
  { name: 'Arbiter\'s Quest', set_number: 'HDH92', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 241, retail_price: 26.99, is_retired: true },
  { name: 'Fiesta', set_number: 'HDP54', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 62, retail_price: 9.99, is_retired: true },
  { name: 'UNSC Gungoose Gambit', set_number: 'HDP59', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 135, retail_price: 16.99, is_retired: true },
  { name: 'Banished Garrison Pack', set_number: 'HDP61', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 133, retail_price: 21.99, is_retired: true },
  { name: 'UNSC Falcon Sweep', set_number: 'HDP62', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 748, retail_price: 79.99, is_retired: true },
  { name: 'Zone Control', set_number: 'HHC35', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 60, retail_price: null, is_retired: true },
  { name: 'Ghost of Requiem', set_number: 'HHC36', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 141, retail_price: 16.99, is_retired: true },
  { name: 'ODST Hive Exterminators', set_number: 'HHC37', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 150, retail_price: null, is_retired: true },
  { name: 'Red Team Warthog Rescue', set_number: 'HHC38', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 331, retail_price: 32.99, is_retired: true },
  { name: 'UNSC Forward Unto Dawn Navy Ship', set_number: 'HHC40', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 720, retail_price: 64.99, is_retired: true },
  { name: 'UNSC Scorpion Clash', set_number: 'HHC42', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 1003, retail_price: 96.99, is_retired: true },
  { name: 'Banished Phantom', set_number: 'HHC43', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 1198, retail_price: 117.99, is_retired: true },
  { name: 'Stockpile', set_number: 'HHJ02', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2022, piece_count: 60, retail_price: null, is_retired: true },
  { name: 'Bazaar Battleground', set_number: 'HKT15', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 77, retail_price: null, is_retired: null },
  { name: 'Decisive Engagement', set_number: 'HKT16', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 76, retail_price: null, is_retired: null },
  { name: 'UNSC Mongoose Outriders', set_number: 'HKT17', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 130, retail_price: null, is_retired: null },
  { name: 'UNSC Hornet Recon', set_number: 'HKT18', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 291, retail_price: null, is_retired: null },
  { name: 'ODST Dutch Miles', set_number: 'HMV56', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 23, retail_price: null, is_retired: null },
  { name: 'ODST Romeo Agu', set_number: 'HMV57', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 22, retail_price: null, is_retired: null },
  { name: 'ODST Mickey Crespo', set_number: 'HNC51', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 24, retail_price: null, is_retired: null },
  { name: 'ODST Rookie', set_number: 'HNC75', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 25, retail_price: null, is_retired: null },
  { name: 'ODST Wombat Overwatch', set_number: 'HMV51', category: 'Mega', theme: 'Mega Construx · Halo', year_released: 2023, piece_count: 129, retail_price: null, is_retired: null }
];

export async function GET(request) {
  if (!SUPABASE_SERVICE_KEY) return Response.json({ error: 'No service key' }, { status: 500 });
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

  // Load existing set numbers to skip duplicates
  const { data: existing } = await supabase
    .from('sets')
    .select('set_number')
    .eq('category', 'Mega');
  const existingNums = new Set((existing || []).map(s => s.set_number?.toUpperCase()));

  const toInsert = HALO_SETS.filter(s => !existingNums.has(s.set_number.toUpperCase()));

  if (toInsert.length === 0) {
    return Response.json({ success: true, inserted: 0, skipped: HALO_SETS.length, message: 'All sets already in DB' });
  }

  // Insert in batches of 100
  let inserted = 0;
  const errors = [];
  for (let i = 0; i < toInsert.length; i += 100) {
    const batch = toInsert.slice(i, i + 100);
    const { data, error } = await supabase
      .from('sets')
      .upsert(batch, { onConflict: 'set_number', ignoreDuplicates: true })
      .select();
    if (error) errors.push(error.message);
    else inserted += data?.length || batch.length;
  }

  return Response.json({
    success: errors.length === 0,
    total: HALO_SETS.length,
    inserted,
    skipped: HALO_SETS.length - toInsert.length,
    alreadyExisted: existingNums.size,
    errors: errors.length ? errors : undefined,
    breakdown: {
      'Mega Bloks · Halo': HALO_SETS.filter(s => s.theme.includes('Bloks')).length,
      'Mega Construx · Halo': HALO_SETS.filter(s => s.theme.includes('Construx')).length,
      years: '2009–2023',
    }
  });
}